CREATE VIEW VW_ANUNCIO AS
SELECT DISTINCT
    AN.ID 				AS ID_ANUNCIO,
    AN.ID_AGRICULTOR	AS ID_AGRICULTOR,
    PD.NOME_PRODUTO		AS NOME_PRODUTO,
    AN.CATEGORIA		AS CATEGORIA_ANUNCIO,
    AN.CLASSIFICACAO	AS CLASSIFICACAO_ANUNCIO,
    AN.ORGANICO			AS ANUNCIO_ORGANICO,
    AN.VALOR			AS ANUNCIO_VALOR,
    ANS.SAZONALIDADE	AS SAZONALIDADE_ANUNCIO
FROM 
    ANUNCIO AN
INNER JOIN 
    PRODUTO PD ON PD.ID = AN.ID_PRODUTO
INNER JOIN 
    ANUNCIO_SAZONALIDADE ANS ON ANS.ID_ANUNCIO = AN.ID;