CREATE OR REPLACE FUNCTION atualizar_media_classificacao()
RETURNS TRIGGER AS $$
DECLARE
    media_rating NUMERIC;
BEGIN
    SELECT AVG(classificacao) INTO media_rating
    FROM anuncio_cliente_classificacao
    WHERE id_anuncio = NEW.id_anuncio;
	AND anuncio_cliente_classificacao.classificacao <> 0
	
    UPDATE anuncio
    SET classificacao = media_rating
    WHERE id_anuncio = NEW.id_anuncio;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR ALTER TRIGGER trigger_atualizar_media_classificacao
AFTER INSERT OR UPDATE ON anuncio_cliente_classificacao
FOR EACH ROW
EXECUTE FUNCTION atualizar_media_classificacao();



CREATE OR ALTER VIEW VW_AGRICULTOR AS
SELECT 
    AG.ID 				AS CODIGOAGRICULTOR,
    AG.CPF				AS CPFAGRICULTOR,
    AG.NOME 			AS NOMEAGRICULTOR,
    AG.DATA_NASCIMENTO	AS DATANASCIMENTO,
    AG.ORGANICO			AS PRODUTORORGANICO,
    AG.ATIVO			AS AGRICULTORATIVO,
    AP.DT_ULT_ACESSO	AS DT_ULTIMOACESSO,
    AP.QTD_ACESSO		AS QTD_ACESSO,
    EDR.CEP				AS CEP_AGRICULTOR,
    EDR.BAIRRO			AS BAIRRO_AGRICULTOR,
    EDR.MUNICIPIO		AS MUNICIPIO
FROM 
    AGRICULTOR AG
INNER JOIN 
    ENDERECO EDR ON EDR.ID = AG.ID_ENDERECO
INNER JOIN 
    ACESSO_PESSOA AP ON AP.ID = AG.ID_ACESSO_PESSOA;
	


CREATE OR ALTER VIEW VW_ANUNCIO AS
SELECT DISTINCT
    AN.ID 				AS ID_ANUNCIO,
    AN.ID_AGRICULTOR	AS ID_AGRICULTOR,
    PD.NOME_PRODUTO		AS NOME_PRODUTO,
    AN.CATEGORIA		AS CATEGORIA_ANUNCIO,
    AN.CLASSIFICACAO	AS CLASSIFICACAO_ANUNCIO,
    AN.ORGANICO			AS ANUNCIO_ORGANICO,
    AN.VALOR			AS ANUNCIO_VALOR,
    ANS.SAZONALIDADE	AS SAZONALIDADE_ANUNCIO
FROM 
    ANUNCIO AN
INNER JOIN 
    PRODUTO PD ON PD.ID = AN.ID_PRODUTO
INNER JOIN 
    ANUNCIO_SAZONALIDADE ANS ON ANS.ID_ANUNCIO = AN.ID;

	

CREATE OR ALTER VIEW VW_CLIENTE AS
SELECT 
    CL.ID 				AS CODIGOAGRICULTOR,
    CL.CPF				AS CPFAGRICULTOR,
    CL.NOME 			AS NOMEAGRICULTOR,
    CL.DATA_NASCIMENTO	AS DATANASCIMENTO,
    AP.DT_ULT_ACESSO	AS DT_ULTIMOACESSO,
    AP.QTD_ACESSO		AS QTD_ACESSO,
    EDR.CEP				AS CEP_AGRICULTOR,
    EDR.BAIRRO			AS BAIRRO_AGRICULTOR,
    EDR.MUNICIPIO		AS MUNICIPIO
FROM 
    CLIENTE CL
INNER JOIN 
    ENDERECO EDR ON EDR.ID = CL.ID_ENDERECO
INNER JOIN 
    ACESSO_PESSOA AP ON AP.ID = CL.ID_ACESSO_PESSOA;



CREATE OR ALTER VIEW VW_ANUNCIO_CLASIFICACAO AS
SELECT 
	* 
FROM ANUNCIO_CLIENTE_CLASSIFICACAO ACC